(add-hook 'find-file-hooks 'auto-insert)
(setq auto-insert 'not-modified)
(setq auto-insert-query nil)

(setq auto-insert-directory "~/autoinsert/")

(setq auto-insert-alist '(("\\.c$" . "initial.c")
                          ("\\.cc$" . "initial.c")
                          ("\\.cpp$" . "initial.c")
                          ("\\.rb$" . "initial.rb")
                          ("\\.java$" . "initial.java")
                          ("\\.h$" . "auto-insert.h")
                          ("\\.hh$" . "auto-insert.h")
                          ("[Mm]akefile" . "makefile.inc")
                          ("\\.pl$" . "auto-insert.perl")
                          ("\\.ks$" . "hlatex-insert.ks")
                          ;("\\.tex$" . "hlatex-insert.tex")
                          ("\\.lisp$" . "elisp-insert.el")
                          ("\\.el$" . "elisp-insert.el")
                          ("\\.html$" . "auto-insert.html")
                          ))
